### ISSUE TITLE
Daemon fails to build on Ubuntu 17.10

### ISSUE THREAD

**Issue by SpeedReam** [Douane/douane-daemon#12]
I installed the software per instructions at Github on 25 Mar 18.
Everything built except the daemon.

I have resolved this build error, but I don't really know what I am doing, and there might be unintended consequences to this fix.

The good news. The software is now running fine on my machine.

The original build error message (from https://pastebin.com/3kfXbdU5):

```
root@Speed-Lap-81:/etc/Douane/douane-daemon# make
g++ -pedantic -Wall -W -g `pkg-config --cflags --libs liblog4cxx dbus-c++-1` -DDOUANE_VERSION=\"0.9.0\" -o main.o -c main.cpp
In file included from /usr/include/dbus-c++-1/dbus-c++/server.h:34:0,
                 from /usr/include/dbus-c++-1/dbus-c++/dbus.h:33,
                 from dbus/dbus_server.h:5,
                 from main.cpp:20:
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h: In static member function ‘static void DBus::Threading<Mx, Cv>::init()’:
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h:262:5: error: no matching function for call to ‘_init_threading(DBus::Mutex* (&)(), void (&)(DBus::Mutex*), void (&)(DBus::Mutex*), void (&)(DBus::Mutex*), DBus::CondVar* (&)(), void (&)(DBus::CondVar*), void (&)(DBus::CondVar*, DBus::Mutex*), bool (&)(DBus::CondVar*, DBus::Mutex*, int), void (&)(DBus::CondVar*), void (&)(DBus::CondVar*))’
     );
     ^
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h:247:13: note: candidate: void DBus::_init_threading()
 void DXXAPI _init_threading();
             ^~~~~~~~~~~~~~~
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h:247:13: note:   candidate expects 0 arguments, 10 provided
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h:249:13: note: candidate: void DBus::_init_threading(DBus::MutexNewFn, DBus::MutexFreeFn, DBus::MutexLockFn, DBus::MutexUnlockFn, DBus::CondVarNewFn, DBus::CondVarFreeFn, DBus::CondVarWaitFn, DBus::CondVarWaitTimeoutFn, DBus::CondVarWakeOneFn, DBus::CondVarWakeAllFn) <near match>
 void DXXAPI _init_threading(
             ^~~~~~~~~~~~~~~
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h:249:13: note:   conversion of argument 3 would be ill-formed:
In file included from /usr/include/dbus-c++-1/dbus-c++/dbus.h:33:0,
                 from dbus/dbus_server.h:5,
                 from main.cpp:20:
/usr/include/dbus-c++-1/dbus-c++/server.h: In copy constructor ‘DBus::Server::Server(const DBus::Server&)’:
/usr/include/dbus-c++-1/dbus-c++/server.h:63:24: warning: unused parameter ‘s’ [-Wunused-parameter]
   Server(const Server &s)
                        ^
Makefile:36: recipe for target 'main.o' failed
make: *** [main.o] Error 1
root@Speed-Lap-81:/etc/Douane/douane-daemon#
```

In resolving this, I used the following post:
https://sourceforge.net/p/dbus-cplusplus/patches/18/

To fix the build error, I modified:
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h

No lines of the original file were changed.
All added lines contain the word 'Fix-16Mar18.01' in a comment.

In the original file, starting at line 232, is the following code:

```cpp
#ifndef DBUS_HAS_RECURSIVE_MUTEX
typedef bool (*MutexFreeFn)(Mutex *mx);
typedef bool (*MutexLockFn)(Mutex *mx);
#else
typedef void (*MutexFreeFn)(Mutex *mx);
typedef void (*MutexLockFn)(Mutex *mx);
#endif//DBUS_HAS_RECURSIVE_MUTEX
```

I changed this code block to:

```cpp
// Fix-16Mar18.01, 26 Mar 18
// Fix-16Mar18.01 See https://sourceforge.net/p/dbus-cplusplus/patches/18/
#define DBUS_HAS_RECURSIVE_MUTEX // Fix-16Mar18.01
#ifndef DBUS_HAS_RECURSIVE_MUTEX
typedef bool (*MutexFreeFn)(Mutex *mx);
typedef bool (*MutexLockFn)(Mutex *mx);
#else
typedef void (*MutexFreeFn)(Mutex *mx);
typedef void (*MutexLockFn)(Mutex *mx);
#endif//DBUS_HAS_RECURSIVE_MUTEX
#undef DBUS_HAS_RECURSIVE_MUTEX // Fix-16Mar18.01
```

With the above fix, the software built, and the product is now in use on my machine.

The altered (working) dispatcher.h is here:
https://pastebin.com/qY86CGEb

**Comment by zedtux** [comment]
Can you please post your kernel version?

**Comment by SpeedReam** [comment]
4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zedtux** [comment]
Heum ... pfff ... sorry I'm tired. Your kernel version doesn't change anything 😃.

So please open a PR, it isn't hurting and could help people. I don't remember anyone complaining about the daemon process compilation but if I see any, then I will redirect them to the PR.
My goal is that someone else than you validate your modification.
(If you know anyone else, please send him the link to this issue 😉)

**Comment by SpeedReam** [comment]
Ok.

I forked and cloned dkms and daemon to my local machine, to a different directory structure.

Both built fine.

So... I thought maybe it had to do with the compile instructions on the wiki.

So a created a new directory structure and built dksm and daemon again using the instructions on the wiki, not using my forked projects.

This time, both built fine.

No clue as to why I couldn't build the first time.

At this point, I'd say everything is working great on Ubuntu 17.10.

**Comment by zedtux** [comment]
Thank you @SpeedReam for this clever approche 👍.
